#
# makefile for host:Linux -> taget:AmigaOS.68k
#
# requires: https://github.com/bebbo/amiga-gcc
#
# usage: make -f Makefile.m68k
#

include makefile.prg.mk

CC = m68k-amigaos-gcc
CFLAGS = -D__PRG_FILE__=\"$(PRG)\" -D__PRG_VERSION__=\"$(VER)\" -O3
LFLAGS = -noixemul

OBJ = utf8toAmigaPL.o

%.o: %.c *.h
	$(CC) -c -o $@ $< $(CFLAGS)

all: $(PRG)

$(PRG): $(OBJ)
	$(CC) -o $@ $^ $(LFLAGS)

clean:
	rm -f *.o
	rm -f $(PRG)
